[package]
name = "orion-field"
version = "0.7.0"
description = "ORION MikroTik Field Assistant"
authors = ["BIONIC"]
edition = "2021"

[lib]
name = "orion_field_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde_json = "1.0.151"
