[package]
name = "orion-field"
version = "0.5.0"
description = "ORION MikroTik Field Assistant"
authors = ["BIONIC"]
edition = "2021"

[lib]
name = "orion_field_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
